### ISSUE TITLE
Vector multiplication is not the same as Dot Product

### ISSUE THREAD

**Issue by atrudel** [42-AI/bootcamp_python#103]
* Day: 01
* Exercise: 02

This is incorrect mathematically:
<img width="615" alt="Capture d’écran 2020-04-23 à 19 44 09" src="https://user-images.githubusercontent.com/25726746/80131636-ced8e480-859a-11ea-8c80-d5f088f406c3.png">

This is a Dot Product, not multiplication.

If you want to multiply two vectors, you need them to be oriented differently (one vertical and the other horizontal). Then, depending on which one is on the left of the multiplication, you either get a matrix or a scalar as a result of the multiplication.

It's very important to make this clear because students will get stuck with strange NumPy behavior if they don't understand the difference between dot product and multiplication.

**Comment by matboivin** [comment]
I read the subject and from what I understand, it was expected from students to compute the dot product and return a scalar.
Fixed the subject in consequence.
