### ISSUE TITLE
subject mistake maybe

### ISSUE THREAD

**Issue by SKTPausanias** [42-AI/bootcamp_python#114]
* Day: 02
* Exercise: ex05

 In the exercise 05 of the day02 of the python bootcamp we need to calculate quartiles 1 and 3 (percentiles 25 and 75) and in the example it says the quartiles for the list [1, 10 , 42 , 59, 300] are 10 and 59, isn't that wrong? think it is (1 + 10) /2 = 5,5 and (59 + 300) / 2 = 179,5 , i have calculated it in a webpage and gives the last results

https://stackoverflow.com/questions/45926230/how-to-calculate-1st-and-3rd-quartiles
Found this stackoverflow post, in the fourth answer it is explained, the python function percentile(arr, 25) does not calculate the q1 / q3 (Moreover, finding quartiles and median can be done in O(n) computations using the Median of medians) can also use this

**Screenshots**
<img width="1081" alt="Screen Shot 2020-11-20 at 17 27 22" src="https://user-images.githubusercontent.com/45973042/99824220-b4c5ab80-2b55-11eb-8570-fbb8f8bb5ca2.png">

What is printed in subject output represents the use of the numpy percentile option, however it asks for the quartiles q1 and q3 and the answer does not correspond to the quartiles
this could be cause of a problem with the percentile option explained here

<img width="1081" alt="Screen Shot 2020-11-20 at 17 30 07" src="https://user-images.githubusercontent.com/45973042/99824486-10903480-2b56-11eb-8f70-aee54b0c3277.png">

**Comment by madvid** [comment]
Fixed in a dev commit
