### ISSUE TITLE
There is a mistake in the subject of ex00 module01

### ISSUE THREAD

**Issue by mo-san99** [42-AI/bootcamp_python#119]
* Day: 01
* Exercise: 00

On the pdf subject, it is written <• recipes_list (dict) : a dictionnary why 3 keys: “starter”, “lunch”, “dessert”.>.
which I guess It should be < a dictionary with 3 keys>

-> screenshot
 
<img width="1680" alt="Screen Shot 2021-03-26 at 19 51 13" src="https://user-images.githubusercontent.com/50895527/112679644-b2a98b80-8e6c-11eb-827f-0c2046151676.png">

**Comment by madvid** [comment]
Thanks for the issue. It is solve and correction has been committed in the dev branch. It will appears in main branch in the next merge.
