### ISSUE TITLE
Small improvement to the vector exercise

### ISSUE THREAD

**Issue by JBarmentlo** [42-AI/bootcamp_python#127]
* Day: 01
* Exercise: 02

It would be more consistent if the row vector was initialized with values = [[0, 1, 2, 3]] instead of [0, 1, 2, 3]
this way for both vector types values[i] corresponds to the i'th row.
I believe it would be more intuitive and make more elegant solutions possible.

```python
# Row vector of shape 1 * n
v1 = Vector([[0.0, 1.0, 2.0, 3.0]])
```

**Comment by madvid** [comment]
Good idea !
Fix:
- github [43038fa] without pdf regeneration.
- gitlab [851953e] on repo (python-module-01) without pdf regeneration.
