### ISSUE TITLE
The_Bank test fails

### ISSUE THREAD

**Issue by JBarmentlo** [42-AI/bootcamp_python#129]
* Day: 01
* Exercise: 06

1:
The value attribute is set at 0 upon creating an account.
A transfer is invalid if an account has insufficient funds.

the testing script inits 2 accounts and tries to transfer money, it fails (as the accounts have no money).
The script somehow excepts a success.

2:
Also the example in test 1 creates a corrupted account (it has an attribute bref that starts with "b")
should that cancel the operation or should the account be fixed on the fly ?

** Fixed:
- [ ] github
- [ ] gitlab

# NOT TO BE FIXED ACCORDING TO THE SUGGESTION 
**SEE COMMENT BELOW AND DO THE SUGGESTED FIX**

fix: remove the set.value at 0
replace accounts
```python
	def __init__(self, name, **kwargs):
		self.id = self.ID_COUNT
		self.name = name
		self.__dict__.update(kwargs)
		Account.ID_COUNT += 1
```

**Screenshots**

**Comment by madvid** [comment]
I think it should be as follow:
```python
class Account(object):
    ID_COUNT = 1

    def __init__(self, name, **kwargs):
        self.id = self.ID_COUNT
        self.name = name
        self.__dict__.update(kwargs)
        if not hasattr(self, 'value'):
            self.value = 0
        Account.ID_COUNT += 1
    
    def transfer(self, amount):
        self.value += amount
```
In this case, if value is specified as kwargs, attribute value is set to the given value, and if it is not given has kwargs, attribute value is instanced to 0 (and declare in the same time).

**Comment by madvid** [comment]
About the script `banking_test1.py`:
```python
from the_bank import Account, Bank

if __name__ == "__main__":
    bank = Bank()
    bank.add(Account(
        'Smith Jane',
        zip='911-745',
        value=1000.0,
        bref='1044618427ff2782f0bbece0abd05f31'
    ))
    bank.add(Account(
        'William John',
        zip='100-064',
        value=6460.0,
        ref='58ba2b9954cd278eda8a84147ca73c87',
        info=None,
        other='This is the vice president of the corporation'
    ))

    if bank.transfer('William John', 'Smith Jane', 545.0) is False:
        print('Failed')
    else:
        print('Success')
```
We can see the first account has an attribute `bref`. This account has an attribute starting with a 'b' and is by definition invalid.
Thus the expected result is an invalid transaction.

For the 2nd test script `banking_test2.py`, the method fix account is called for both account, thus a `Failed` follow by a `Success` is expected.

**Comment by madvid** [comment]
fixed:
- commit [34f195e] on github
- commit [7126eac] on gitlab (python-module-01) without pdf regeneration
