### ISSUE TITLE
D00 - ex00

### ISSUE THREAD

**Issue by quentinbragard** [42-AI/bootcamp_python#13]
Dans l'exemple, la même ligne de commande donne 2 comportements différents: 

$> ./installer.sh install-python
   [v] python is installed.
$> ./installer.sh install-python
   Python is already installed, do you want to reinstall it ?

**Comment by Talasta** [comment]
`[v] python is installed.`
Cette ligne signal au user que python vient d'être installé.

**Comment by Talasta** [comment]
Fixed
