### ISSUE TITLE
Critical Error in vector correction

### ISSUE THREAD

**Issue by JBarmentlo** [42-AI/bootcamp_python#134]
* Day: 01
* Exercise: 02

1:
(b - a + 1) should be (b - a)

2:
a tuple (a, a) should create a vector of size 1 according to correction. False, should be removed.

Subject
```bash
Vector((10,15)) -> the vector will have values = [[10.0], [11.0],[12.0], [13.0], [14.0]]
```
10 - 15 + 1 = 6. 
According to correction the size should be 6, the vector in the example on the subject is size 5

**Screenshots**

**Comment by madvid** [comment]
Fixed:
- gitlab [e3cb30a] - repo: python-module-01 - no pdf regeneration
