### ISSUE TITLE
Critical error in Vector day 01

### ISSUE THREAD

**Issue by JBarmentlo** [42-AI/bootcamp_python#135]
* Day: 01
* Exercise: 02

SUBJECT:
```python
_mul__
__rmul__
# mul : only scalars.
```

CORRECTION:
```
Vector(1) * Vector(1) should correspond to the dot product
```
The dot product is in Vector.dot()

again the correction grid gives false to a student following the subject to the letter.

**Comment by qfeuilla** [comment]
what should i do, just ignore this question for the moment and then precise that the * is the dot product in the subject ?

**Comment by madvid** [comment]
Fixed:
- gitlab [e3cb30a] - repo: python-module-01 - no pdf regeneration
