### ISSUE TITLE
Day00 - ex00 : subject: pip

### ISSUE THREAD

**Issue by Fulguritude** [42-AI/bootcamp_python#14]
"You will also be able to install packages via pip using this script."
Vous voulez dire qu'on devrait par le même installer.sh pouvoir appeler pip ? Selon quelle syntaxe ? Tout argument qui n'est pas "install-python" appelle `pip3 [mon_argument]` ?

**Comment by Talasta** [comment]
Added to the check list https://github.com/42-AI/bootcamp_python/issues/18#issue-506815896
