### ISSUE TITLE
Day02 ex00 subject

### ISSUE THREAD

**Issue by JBarmentlo** [42-AI/bootcamp_python#141]
* Day: 02
* Exercise: 00

Subjects asks to return None in case of problems (in function docstrings) it also asks to raise errors similar to the original functions.
The correction makes no mention of the None return (should be double checked)

Solution:
Remove Error type emulation to make the exercise more about understanding the functions and less about reverrse engineering error messages

**Comment by qfeuilla** [comment]
Are you sure it is the good exercise ? If it is, so it seems fixed
