### ISSUE TITLE
Missing cmd line in subject exo4 Day01

### ISSUE THREAD

**Issue by JBarmentlo** [42-AI/bootcamp_python#144]
* Day: 01
* Exercise: 04

If you follow the instructions in the screenshot.
```bash
pip show -v my_minipack
```
does nothing.

Solution :
add this line before
```bash
 pip install ./dist/my_minipack-1.0.0-py3-none-any.whl
```

**Comment by qfeuilla** [comment]
I think that this line must be written in the build.sh by the student
