### ISSUE TITLE
module00 - ex04

### ISSUE THREAD

**Issue by madvid** [42-AI/bootcamp_python#145]
* Day: 00
* Exercise: 04

Example with negative number

**Examples**
If applicable, add examples to help explain your problem.

```python
print("Code example")
```

**Screenshots**

**Comment by AugustinLopez** [comment]
Given the following case, is this behavior okay for the remainder ?

```
> python3 operations.py 21 -42
Sum:         -21
Difference:  63
Product:     -882
Quotient:    -0.5
Remainder:   -21
```
