### ISSUE TITLE
Day00, Ex01:

### ISSUE THREAD

**Issue by Fulguritude** [42-AI/bootcamp_python#15]
```
$> python exec.py "Hello World!"
   !DLROw OLLEw
   $> python exec.py "Hello" "my Friend"
   DNEIRf YM OLLEw
```

devrait être

```
$> python exec.py "Hello World!"
   !DLROw OLLEh
   $> python exec.py "Hello" "my Friend"
   DNEIRf YM OLLEh
```

(h plutôt que w)

**Comment by Fulguritude** [comment]
Et question: cela veut dire qu'on rajoute un espace entre chaque argument ? ie " my friend" ou "my friend" ?

**Comment by Talasta** [comment]
Added to the check list https://github.com/42-AI/bootcamp_python/issues/18#issue-506815896
