### ISSUE TITLE
m00/ex07 filterwords - more precision on punctuation

### ISSUE THREAD

**Issue by mli42** [42-AI/bootcamp_python#153]
* Day: 00
* Exercise: 07

In this exercise, it is asked to remove punctuation from the input
But in the correction page, we should test punctuation within words

The subject should have this special case in the exemple:
If the input is `..A..B..`, should it be treated as `A..B` or `AB` or `A B`

In my opinion, it should be `A B` because in a text like `...end of sentence.Begin of sentence`, `sentence` and `Begin` aren't the same word

**Comment by AugustinLopez** [comment]
While it would be *logical* to treat punctuation as a word separator, it also make the exercise easier than it needs to be.
