### ISSUE TITLE
Module03ex00: Tests ne compilant pas tel quel

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_python#159]
* Day: 03
* Exercise: 00

Erreur de compilation du sujet. le main de test propose les tests suivant:
```
npc.from_list((1, 2), (3, 4))
```
le header fournis lui est 
```
from_tuple(tpl):
```
Erreur:
```
TypeError: from_list() takes 2 positional arguments but 3 were given
```

Aussi:
```
shape = (3, 5)
npc.from_shape(shape)
```
avec pour header
```
from_shape(shape, value):
```
Erreur:
```
TypeError: from_shape() takes 3 positional arguments but 2 were given
```

## Fixed on:
- [ ] Github
- [x] Gitlab

**Comment by madvid** [comment]
- La première remarque relève effectivement d'une erreur.
 - La seconde remarque sur la méthode `from_shape` est infondée, une compréhension incomplète de ce qui est demandé dans l'exercice en est la cause:
 

> from_shape(shape, value): returns an array filled with the same value, The first
argument is a tuple which specifies the shape of the array, and the second argument
specifies the value of all the elements. **This value must be 0 by default,**

**Comment by madvid** [comment]
fixing first error in markdown exercise on github + fixing error in latex file subject and regenerate pdf on gitlab
