### ISSUE TITLE
D00-ex04

### ISSUE THREAD

**Issue by quentinbragard** [42-AI/bootcamp_python#16]
Dans l'énoncé, on demande "a function that takes 2 numbers as parameters" mais on ne sait pas comment traiter les float (si par exemple on essaye python operations.py 10.5 3). Perso, je considère qu'on attend 2 int en paramètres :)

**Comment by Talasta** [comment]
Added to the check list https://github.com/42-AI/bootcamp_python/issues/18#issue-506815896
