### ISSUE TITLE
Module02 ex04: minipack: ptypo dans la commande d'exemple

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_python#160]
* Day: 02
* Exercise: 04

La commande test fournis utilise `env` au lieu de `venv`

**Examples**
```
python -m env tmp_env && source tmp_env/bin/activate
```

## Fixed on:
- [x] Github
- [x] Gitlab

**Comment by madvid** [comment]
markdown corresponding to the exercise has been updated + latex file on the repository python-module-01 has been updated and pdf regenerated
