### ISSUE TITLE
Python03ex03 ColorFilter: Inconsistencies between the different authorized operators

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_python#167]
* Day: 03
* Exercise: 03

The subjets has some minors inconsistencies. `to_blue(array)` specifies `Authorized operator: None` while `to_celluloid(array)` doesn't mention anything

**Screenshots**
![image](https://user-images.githubusercontent.com/38692785/143421496-73eae758-6fdc-4e0d-963f-e3ee911e16da.png)
![image](https://user-images.githubusercontent.com/38692785/143421556-18e92ead-4acc-47b0-8ba7-b2aee1991b0a.png)

**Comment by qfeuilla** [comment]
i think it is because every operators are authorized so there is not really any reason to pu Authorized operator : all
