### ISSUE TITLE
[Module03_Ex03] `ColorFilter.to_grayscale()` inconsistencies between function prototype, subject and correction

### ISSUE THREAD

**Issue by manki23** [42-AI/bootcamp_python#168]
* Day: 03
* Exercise: 03

#### Correction says
``` python
im = cf.to_grayscale(array, "w", weights = [0.2126, 0.7152, 0.0722])
```

#### Subject says 
``` python
def to_grayscale(array, filter, **kwargs):
    """
    ...
    For filter = ’weight’/’w’: performs a weighted mean of RBG channels.
    ...
    weights: [kwargs] list of 3 floats where the sum equals to 1,
    corresponding to the weights of each RBG channel
    ...
    """
```

#### Subject example shows
``` python 
cf.to_grayscale(arr, ’weighted’, [0.2, 0.3, 0.5])
```

-> Second argument brings confusion since subject uses `weight` and not `weighted`
-> Third argument brings confusion because this example implies `*args` and not `**kwargs`

The subject example should be change to :
``` python 
cf.to_grayscale(arr, ’weight’, weights = [0.2, 0.3, 0.5])
```
for consistency.

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by madvid** [comment]
partially fixed in the PR #221 , need to fix the part about **\*args and \*\*kwargs**
