### ISSUE TITLE
Add informations to common rules about error management

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_python#170]
* Day: 03
* Exercise: xx

The subjects doesn't really asks for the exercices to do eeror management but the correction does. It would be wise to add this as a common rule to all exercices.
"Unless specified otherwise, the error management must be perfect"

**Comment by qfeuilla** [comment]
The error managment must be specific of the exercise with precise case to handle, i don't think a vague message on the begining of the day is fare and clear
