### ISSUE TITLE
day03ex03: static methods or classic methods ?

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_python#174]
* Day: 03
* Exercise: 03

The methods headers are given as static methods/class methods in the given code
![image](https://user-images.githubusercontent.com/38692785/144472980-61b4c09d-367c-460e-9ef9-9479683b6d5c.png)
but the examples uses an instance
![image](https://user-images.githubusercontent.com/38692785/144473100-02789297-2915-4f4b-a60b-2fc216a85a6e.png)

**Comment by madvid** [comment]
dupplicate with the PR #215
