### ISSUE TITLE
Python03 ex03

### ISSUE THREAD

**Issue by Mazoise** [42-AI/bootcamp_python#240]
* Day: 03
* Exercise: 03

Le prototype de to_grayscale est pas bon, on devrait avoir *args plutôt que **kwargs en entrée vue qu'il y a pas de key sur l'argument weight

**Examples**
If applicable, add examples to help explain your problem.

Au lieu de ça :
```python
def to_grayscale(self, array, filter, **kwargs):
```
Il faut ça:
```python
def to_grayscale(self, array, filter, *args):
```
mais le plus cohérent selon moi serait de changer le prototype à :
```python
def to_grayscale(self, array, filter, weight=None):
ou
def to_grayscale(self, array, weight=None):
```
Mettre *args est utile si on ne connait pas le nombre d'argument qu'on va recevoir en paramètre, ce n'est pas le cas dans cet exo.

**Comment by qfeuilla** [comment]
Je pense que kwargs fonctionne aussi, je me cette issue en enhancment

**Comment by madvid** [comment]
> Il faut ça:
> ```python
> def to_grayscale(self, array, filter, *args):
> ```
> mais le plus cohérent selon moi serait de changer le prototype à :
> ```python
> def to_grayscale(self, array, filter, weight=None):
> ou
> def to_grayscale(self, array, weight=None):
> ```
> Mettre *args est utile si on ne connait pas le nombre d'argument qu'on va recevoir en paramètre, ce n'est pas le cas dans cet exo.

Alors c'est une vision de l'exercice que je trouve discutable, mais effectivement ça manque de cohérence

**Comment by madvid** [comment]
J'ai fait une PR pour forcer l'utilisation de kwargs
