### ISSUE TITLE
Python 02 ex02

### ISSUE THREAD

**Issue by Mazoise** [42-AI/bootcamp_python#241]
* Day: 02
* Exercise: 02

Dans le sujet de correction il y a écrit :
```
username is obtained via the environment variable (os.environ["USER"]).
```
alors qu'il y a au moins 5 manières différentes de récuper le username dont plusieurs utilisent la librairie os
https://www.geeksforgeeks.org/how-to-get-the-current-username-in-python/

**Comment by qfeuilla** [comment]
already fix in the new  (coming soon) version
