### ISSUE TITLE
Wrong dot product expected result

### ISSUE THREAD

**Issue by lienardale** [42-AI/bootcamp_python#247]
(1,3).dot((2,4)) equals 14, not 13 (https://www.calculatorsoup.com/calculators/algebra/dot-product-calculator.php?input=%281%2C3%29%282%2C4%29&sf=0&action=solve) 

https://github.com/42-AI/bootcamp_python/blob/24d18a54edaace55a19ef452ecdeec7b419b4d63/module01/subject/en.subject.tex#L494

**Comment by madvid** [comment]
FIXED, PR en cours, merci Alex
