### ISSUE TITLE
add link in day00/ex00 

### ISSUE THREAD

**Issue by Talasta** [42-AI/bootcamp_python#30]
https://docs.conda.io/projects/conda/en/latest/user-guide/install/macos.html

**Comment by matboivin** [comment]
Do we replace the current link by the one mentionned above here:

> In order to have a simple life lets create a script the check if the right python version is installed and install it if it is not, you are going to use miniconda installer :

**Comment by matboivin** [comment]
I replaced the current link by the one mentionned above here:

> In order to have a simple life lets create a script the check if the right python version is installed and install it if it is not, you are going to use miniconda installer :

Let me know this is what was expected.
