### ISSUE TITLE
Doute sur output exo5 / kata 3

### ISSUE THREAD

**Issue by wadges** [42-AI/bootcamp_python#31]
"Write a program to display the string above right-aligned with '-' padding and a total length of
42 characters: "

L exemple d'output donne pour  "python kata03.py | wc -c" donne 42 pour resultat
me semble incorrect, selon moi le resultat attendu devrait etre 43 (42 char + \n)

➜  ex05 python kata03.py | cat -e
--------------------------The right format$
➜  ex05 python kata03.py | wc -c
      43

Je ne suis pas sur de moi sur celle la mais je vous invite a check

**Comment by wadges** [comment]
A priori pas de probleme, je pensais a tort que l'on attendais un \n a la fin de l output

**Comment by Talasta** [comment]
En effet, je close du coup
