### ISSUE TITLE
Day04 - Updates post-testing

### ISSUE THREAD

**Issue by matboivin** [42-AI/bootcamp_python#32]
## Global notes:

* ex04 is simpler than ex03

### ex02:
- [x] 1. Is it necessary to handle errors?
- [x] 2. Drop duplicated values and update the result in the example (`0.02307969707897584`) to `0.01935634328358209`.
See: https://github.com/42-AI/bootcamp_python/issues/5#issuecomment-543690029

### ex04:
- [x] 1. The examples are a bit misleading: `sp.where(2162)` is not in the dataset and `sp.when('Atlanta')` olympic games took place in 1996, neither in 1903 nor 2042.
It should be mentioned not to trust the examples.
See: https://github.com/42-AI/bootcamp_python/issues/5#issuecomment-543748991

### ex05:
- [x] 1. If duplicated medals are not handled for the team games, this exercise is too similar to ex03.
- [x] 2. The CSV data is not up-to-date.
- [x] 3. Precise in the instructions if duplicated medals per team games should be handled and add an example from the dataset.
If duplicated medals are dropped: France 2008: {'G': 25, 'S': 24, 'B': 28} -> {'G': 7, 'S': 16, 'B': 20}
See: https://github.com/42-AI/bootcamp_python/issues/5#issuecomment-543766438

### ex06:
- [x] 1. Add concrete examples:
Maybe add some plots (`mathplotlin.pyplot.hist()`) screenshots for more clarity. All images must be put in an `assets` directory at the root of the day folder.
- [x] 2. The word `feature` from ML and data science terminology can be a little bit confusing at the beginning.

### ex07:
- [ ] 1. Add concrete examples:
Maybe add some plots (`mathplotlin.pyplot.hist()`) screenshots for more clarity. All images must be put in an `assets` directory at the root of the day folder.

**Comment by Talasta** [comment]
Let's put on the side the last comment and merge this.
