### ISSUE TITLE
Day03 - Numpy

### ISSUE THREAD

**Issue by Talasta** [42-AI/bootcamp_python#4]
**Notions:**

- [ ] dimension flottante
- [x] matrices à 3-4 dimensions
- [x] vstack et hstack
- [x] manipuler une image
- [ ] broadcasting
- [x] slicing
- [ ] normalize

**Comment by atrudel** [comment]
I wrote an outline of day03 with a brief description of the exercises. (In French so that we don't confuse the ideas with the actual exercise instructions)

**Comment by Fulguritude** [comment]
PDF title says Day01 instead of Day03

**Comment by Fulguritude** [comment]
Filename for ex01 is "imageProcesor.py", it should be "ImageProcessor.py"

**Comment by Fulguritude** [comment]
ex02: in the "crop" function, "dimensions" is an ambiguous name. It should be instead called "new_image_size" and the exercise should ask for error handling if new_image_size.width > initial_img_size.width etc

**Comment by lacretelle** [comment]
ex02: ça manque d'exemples, explications pour la gestion des erreurs/parsing des donnees

**Comment by Fulguritude** [comment]
A partir de l'exercice ex02, mentionner le choix entre `func(self, arg)` et l'existence du décorateur `@staticmethod func(arg)`

**Comment by Fulguritude** [comment]
ex03: to_{color} functions are mismatched: function name is never the same as the filter in the description

**Comment by lacretelle** [comment]
La case "Notions" dans ce day est vraiment bien, en tant que noob ça aide pour trouver une piste

**Comment by remyoster** [comment]
ex 02: Perso je trouve les noms de fonction explicite, mais la description inexplicite ;P rappeler qu'on bosse avec une image peut faciliter la comprehension.

**Comment by Fulguritude** [comment]
Je suis pour autoriser arange ou linspace pour ex03 : celluloid

**Comment by Fulguritude** [comment]
ex03: grayscale: no example given for a custom weigth vector: should I understand it should always be 0.299R + 0.587G + 0.114B ?

**Comment by Talasta** [comment]
Link => https://github.com/42-AI/bootcamp_python/issues/28#issue-508990679
