### ISSUE TITLE
create a readme for the repo

### ISSUE THREAD

**Issue by Talasta** [42-AI/bootcamp_python#46]
create a readme for the repo

And remove the file PYTHON2019.md
We also want to give credits to the contributors and the beta-testers.

**Comment by matboivin** [comment]
Added a first version of the README. Anyone feels free to modify it, add/remove content.

**Comment by matboivin** [comment]
To contributors and beta-testers, feel free to add your name in the Acknowledgements following this format:

```
First name Surname (username@student.42.fr)
```

You can also replace the First name and Surname by a nickname if you want to.
