### ISSUE TITLE
Compress .pdfs

### ISSUE THREAD

**Issue by backslash-zero** [42-AI/bootcamp_python#53]
Noticed the pdfs are ~8mb which is a lot for a text file, and sometimes slow to open: I suggest to compress them with any free online tool.
For instance [here](https://www.ilovepdf.com/compress_pdf)
Cheers! 🐍

**Comment by matboivin** [comment]
Thank you!

**Comment by Talasta** [comment]
closing: has been done ine the pdfbuilder repo
