### ISSUE TITLE
Day01 ex02 (Vector)

### ISSUE THREAD

**Issue by roduquen** [42-AI/bootcamp_python#54]
__add__
__radd__
# add : scalars and vectors, can have errors with vectors.
__sub__
__rsub__
# sub : scalars and vectors, can have errors with vectors.
__truediv__
__rtruediv__
# div : only scalars.
__mul__
__rmul__
# mul : scalars and vectors, can have errors with vectors,
# return a scalar **is ( >> if )**we perform Vector * Vector (dot product)
__str__
__repr__

**Comment by Talasta** [comment]
fixed
