### ISSUE TITLE
Rush00 - Scrapping

### ISSUE THREAD

**Issue by Talasta** [42-AI/bootcamp_python#6]
Scope has to be defined

_curl - class Sessions, regex : re lib_

### Inspirations:
- D03 Ex03 de la piscine `django` [[le sujet](https://github.com/Binary-Hackers/42_Subjects/blob/master/01_Piscines/Python-Django/D03.pdf) ou [une solution](https://github.com/fxbabin/Piscine_python_django/blob/master/d03/ex03/roads_to_philosophy.py)]
- Un workshop d'Harvard (très bien fait) [[static](http://tutorials.iq.harvard.edu/Python/PythonWebScrape/PythonWebScrape.html) ou [jupyter notebook](http://tutorials-live.iq.harvard.edu:8000/user/QVncZY4IxsPo/notebooks/workshops/Python/PythonWebScrape/PythonWebScrape.ipynb)]

**Comment by Talasta** [comment]
Inspiring: https://github.com/fxbabin/Piscine_python_django/blob/master/d03/ex03/roads_to_philosophy.py

**Comment by matboivin** [comment]
Can I delete the branch `rush/00/phase1`?

**Comment by matboivin** [comment]
Branch `rush/00/phase1` has been deleted. I close this issue since we don't plan to create a rush subject for now.

**Comment by matboivin** [comment]
Optional rush.
