### ISSUE TITLE
Relecture rapide 08-01-2020

### ISSUE THREAD

**Issue by Fulguritude** [42-AI/bootcamp_python#67]
day03 ex02:`permorm`; did you mean `perform` ?

day03 ex03: "(.arange ?)" qui flotte dans le doute

day04 ex06: pourrait avoir des page-end afin de mieux organiser les diagrammes et leurs titres

day04 ex07: "BONUS: Your functions can also accept a list of numerical variables, and output comparison plots for each feature against different"...

**Comment by matboivin** [comment]
Thanks a lot!

**Comment by matboivin** [comment]
- [x] day03 ex02:`permorm`; did you mean `perform` ?
- [x] day03 ex03: "(.arange ?)" qui flotte dans le doute

**Comment by matboivin** [comment]
- [x] day04 ex07: "BONUS: Your functions can also accept a list of numerical variables, and output comparison plots for each feature against different"...

**Comment by matboivin** [comment]
TODO:

- [ ] day04 ex06: pourrait avoir des page-end afin de mieux organiser les diagrammes et leurs titres
