### ISSUE TITLE
License covers software (and its docs) but not documents alone

### ISSUE THREAD

**Issue by Exagone313** [42-AI/bootcamp_python#68]
IANAL

MIT license covers `this software and associated documentation files` but the repository only contains documents. Also one could argue sparse pieces of source code in these documents is not software.

You may consider using a Creative Commons license like CC-BY-SA.

And why not tell that included source code is in public domain so anyone can use it? In a tutorial, source code will be copied without following the license, so better to ease the task legally.

If you include pdf build scripts, these indeed will be software though.

**Comment by Talasta** [comment]
Thanks for your comment ! We are going to change this !

**Comment by matboivin** [comment]
Thanks a lot!

**Comment by Talasta** [comment]
Done !
