### ISSUE TITLE
text_analyzer example with multiple arguments

### ISSUE THREAD

**Issue by madvid** [42-AI/bootcamp_python#70]
* Day: 00
* Exercise: 03

Apparently some confusion on what text_analyzer should do when the number of arguments is greater than 1.

**Examples**
text_analyzer("this is the first sentence.", "this is a second sentence.").

**Comment by matboivin** [comment]
Thank you for raising this!

**Comment by madvid** [comment]
Or maybe be clear that one and only one argument has to be given to text_analyzer
