### ISSUE TITLE
Day01 - New exercises needed [Bootcamp ML Preps] 

### ISSUE THREAD

**Issue by ppeigne** [42-AI/bootcamp_python#75]
In order to make the Machine Learning bootcamp easier, we need to add two exercises in the Day01. 

- [x] **The Matrix:** same spirit as The vector and just after it.   
This class methods must includes matrix-matrix operation AND matrix-vector operations as well. 

- [ ] **K-Nearest Neighbors** as a final exercise.  
The dataset would be taken from the ML Bootcamp (Blue pills dataset or Spaceship dataset).
The exercise must include two methods:  
   - [ ] .predict()
   - [ ] .score() - using a metric such as MSE

**Comment by matboivin** [comment]
Authorized operations in latex have been added to the Vector (day01/ex02).

**Comment by matboivin** [comment]
The Matrix needs some verification but most of the exercise is done.

**Comment by matboivin** [comment]
Hi @ppeigne 
Can I split the issue and create a new one about KNN only?

**Comment by ppeigne** [comment]
Yes of course :)

**Comment by matboivin** [comment]
New issue for KNN only: #80
