### ISSUE TITLE
Day02 - New exercise needed [Bootcamp ML Preps] 

### ISSUE THREAD

**Issue by ppeigne** [42-AI/bootcamp_python#76]
In order to make the Machine Learning bootcamp easier, we need to add one exercise in the Day02. 

- [x] **TinyStatistician:** as a final exercise.   
It is a small class with few basics methods to implement in.  
   - [x] Mean
   - [x] Median
   - [x] Quartiles (25% and 75%)
   - [x] Variance
   - [x] Standard Deviation

**Comment by matboivin** [comment]
Thanks a lot!
