### ISSUE TITLE
Day03 - New exercise needed [Bootcamp ML Preps] 

### ISSUE THREAD

**Issue by ppeigne** [42-AI/bootcamp_python#77]
In order to make the Machine Learning bootcamp easier, we need to add exercise and to remove one in the Day03. 

** Remove **  
- [x] **Advanced modifications:**

** Add **  
- [x] **K-means:** as a final exercise.  
The dataset would be taken from the ML Bootcamp (Solar sytem census dataset).  
The exercise must include two methods:  
   - [x] .fit()
   - [x] .predict()
   - [x] .score() - using distortion metric

**Comment by matboivin** [comment]
Removed the 4th exercise Advanced modifications and replaced it by K-means clustering. Also added the corresponding dataset.

**Comment by matboivin** [comment]
Thanks for your support!
