### ISSUE TITLE
Answer for Q0 &&1 of d00 seem to be the same?

### ISSUE THREAD

**Issue by luisroel91** [42-AI/bootcamp_python#84]
* Day: 00
* Exercise: 00

The first question is: Output a list of installed packages
The second question is: Output a list of installed packages and their versions

Output of command "conda list":

<img width="469" alt="Screen Shot 2020-03-09 at 4 36 26 PM" src="https://user-images.githubusercontent.com/44761184/76266281-31149a80-6224-11ea-8aaf-698e5b4bfab1.png">

Are the writers intending for us to grep the output of conda list or is there something I'm missing?

Thank you!

**Comment by Talasta** [comment]
The idea was to use `pip` instead of `conda` to show the packages and their versions.

**Comment by luisroel91** [comment]
"As an introduction, complete the following questionnaire using Python and pip"

Missed this line...thank you!
