### ISSUE TITLE
We can perform additions between scalar and vectors

### ISSUE THREAD

**Issue by eduriez** [42-AI/bootcamp_python#85]
* Day: 01
* Exercise: 02

We can perform additions between scalar and vectors, not only between vectors.
Moreover, in the 2nd screenshot, we have some typo : it is x1 + **y1**, no x1 + **x1**

![Screen Shot 2020-03-10 at 3 07 02 PM](https://user-images.githubusercontent.com/33417059/76320399-f0c72200-62e0-11ea-9f9e-ff49b52f94b8.png)
![Screen Shot 2020-03-10 at 3 07 35 PM](https://user-images.githubusercontent.com/33417059/76320411-f4f33f80-62e0-11ea-881e-85128ea09223.png)

**Comment by Talasta** [comment]
Thx will be fixed.

**Comment by matboivin** [comment]
I fixed the operations, replacing x by y when necessary.
