### ISSUE TITLE
Day01: ex04; Implementing a shuffle algorithm without the "random" module

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_python#86]
* Day: 01
* Exercise: 04

The subjects asks to implement a yield function called generator returning word depending on the parameter given (Nothing, shuffle or ordered)
Shuffle asks for a random order, but the subjects has `Forbidden Functions: random`. Implementing a random without the `random` module ?...
Just this, thank you ! (Excellent work on the subjects btw)

**Comment by Talasta** [comment]
We should make a better subject for the generator... I will think about it.

**Comment by matboivin** [comment]
For now, I think they can implement: https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle
I added` random.randint` as authorized.
