### ISSUE TITLE
Ordering error in D01/ex04

### ISSUE THREAD

**Issue by eduriez** [42-AI/bootcamp_python#87]
* Day: 01
* Exercise: 04

"Le Lorem Ipsum est simplement du faux texte."

Ordered...

"**Ipsum Le Lorem** du est faux simplement texte.", not "du est faux simplement texte. **Ipsum Le Lorem**" (cf uppercase < lowercase in ascii order)

![Screen Shot 2020-03-11 at 12 36 27 PM](https://user-images.githubusercontent.com/33417059/76413285-71475a80-6395-11ea-8bc5-804aed9ea3c7.png)

**Comment by matboivin** [comment]
Thank you for opening this issue. The output has been replaced.

**Comment by matboivin** [comment]
Changes have been merged into `dev`.
