### ISSUE TITLE
Two errors handleable in D02/ex03

### ISSUE THREAD

**Issue by eduriez** [42-AI/bootcamp_python#89]
* Day: 02
* Exercise: 03

Two errors are handleable : line with too many elements **and** line with too few elements.
![Screen Shot 2020-03-11 at 7 54 06 PM](https://user-images.githubusercontent.com/33417059/76452878-18e27e00-63d2-11ea-907a-94c27b6d5a80.png)

**Comment by matboivin** [comment]
Thank you for opening this issue. It has been handled and we'll be visible in the next merge.

**Comment by matboivin** [comment]
Changes have been merged into `dev`.
