### ISSUE TITLE
How to contribute ?

### ISSUE THREAD

**Issue by Talasta** [42-AI/bootcamp_python#9]
First assign your self to the related issue.

In order to create content for the piscine you will have to create a branch with the following template :  `day/XX/phaseY`
_(where XX is the number of the day and Y the related Phase)_

The day folder will have the following architecture : 
```
└── day00
    ├── day00.md
    ├── ex00
    │   └── ex00.md
    ├── ex01
    │   └── ex01.md
    └── ex02
        └── ex02.md
```

**Comment by blefeuvr** [comment]
Why a subdir for each exercice ?

**Comment by matboivin** [comment]
Hi! Would it be relevant to move 'How to contribute' and the templates (day, exercises) in a Wiki?

**Comment by Talasta** [comment]
Yes ! It’s a good idea !

**Comment by Talasta** [comment]
In wiki now
