### ISSUE TITLE
Day00 Exercise01 error

### ISSUE THREAD

**Issue by batboy118** [42-AI/bootcamp_python#94]
* Day: 00
* Exercise: 01

in the examples of Exercise01, `python exec.py "Hello World!" | cat -e` is not working well. I think `\` should be added in front of `!` like `python exec.py "Hello World\!" | cat -e`

**Screenshots**
![image](https://user-images.githubusercontent.com/53181778/79113506-0934cb80-7dbc-11ea-83de-f1e6b25c45bc.png)

**Comment by madvid** [comment]
what problem do you have without the "\" ? can you share a screenshot ?

**Comment by batboy118** [comment]
![image](https://user-images.githubusercontent.com/53181778/79118406-d34a1400-7dc8-11ea-83ff-8aef43ffb89c.png)
It is OK without the `""`. but like the example, when I use `!` inside of the `" "`, it happens.
