### ISSUE TITLE
Day00 ex00 change the order of the shell commands

### ISSUE THREAD

**Issue by atrudel** [42-AI/bootcamp_python#97]
* Day: 00
* Exercise: 00

In the Conda manual install, the PDF suggests several steps to install Python:
**Step 3** is problematic because it asks to install jupyter, numpy and pandas BEFORE conda has been added to the PATH (steps 4 and 5).

I'd suggest we move *Step 3* to the very end, i.e. after *Step 6*.

<img width="446" alt="Capture d’écran 2020-04-13 à 18 40 57" src="https://user-images.githubusercontent.com/25726746/79139281-51e98600-7db6-11ea-831a-f0232d95596b.png">

**Comment by matboivin** [comment]
Issue has been fixed in branch `clean/afterbootcamp`. Will be merged into master.
